product/urls.py
from django.urls import path

from .views import products, search


app_name = 'product'

urlpatterns = [

    # CBV
    # path('product-list', ProductList.as_view(), name='product-list'),

    # FBV
    path('', products, name='products'),

    path('<int:query_id>', products, name='products_query_id'),

    path('search', search, name='search'),

]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

# from .views import HomeView


urlpatterns = [

    path('admin/', admin.site.urls),

    # Home
    # path('', HomeView.as_view(), name='home'),

    # App1 (product)
    path('', include('product.urls', namespace='product')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# product category
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


# product brand
class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Brands'

    def __str__(self):
        return self.name


# product
class Product(models.Model):

    class Status(models.TextChoices):
        PENDING = 'Pending', _('PENDING')
        PUBLISHED = 'Published', _('PUBLISHED')
        STOCK_OUT = 'Stock Out', _('STOCK_OUT')

    name = models.CharField(max_length=100)
    slug = models.TextField(null=True, blank=True)
    image = models.ImageField(default='default.png', null=True, blank=True, upload_to='product_images')
    description = models.TextField(max_length=100)
    price = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=10)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name


# filtering
class QueryStrings(models.Model):
    data = models.CharField(max_length=200)
    report = models.TextField(max_length=500)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.data

product/views.py
from urllib import parse
from urllib.parse import urlencode
from django.contrib import messages
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404

from .models import (
    Category,
    Brand,
    Product,
    QueryStrings
)


# CBV
# class ProductList(ListView):
#     model = Product
#     template_name = 'product_list.html'


# FBV
def products(request, query_id=None):
    products = Product.objects
    # print(products)
    # print(type(products))

    if query_id:
        query_dict = process_query_string(query_id)
        products = products.filter(**query_dict)

    products =  products.all()
    brands = Brand.objects.filter()
    categories = Category.objects.filter()
    statuses = Product.Status.choices

    context = {
        'products': products,
        'brands': brands,
        'categories': categories,
        'statuses': statuses
    }

    template = 'product_list.html'

    return render(request, template, context)


# submitted selection data
def search(request):
    print(request.POST)

    fields_data = search_form_fields_filter(request.POST)
    query_id = store_querystring(fields_data)

    return redirect('product:products_query_id', query_id)


# returns list of custom field names
def search_form_fields():
    return ['brand', 'category', 'status']


def search_form_fields_filter(query_dict):
    # print('TEST:', query_dict)
    query_string = {}

    for i in search_form_fields():
        if query_dict.get(i):
            query_string.update({i: query_dict.get(i)})

    return query_string


def store_querystring(data):
    query_data = QueryStrings.objects.create(data=urlencode(data))
    # print(query_data)
    # print(query_data.id)
    return query_data.id


def process_query_string(query_id):
    query_string = QueryStrings.objects.get(pk=query_id)
    return dict(parse.parse_qsl(query_string.data))

src/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q


class HomeView(TemplateView):
    template_name = 'home.html'

product/templates/product_list.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}


{% block content %}

    <!--Heading-->

    {#    <br>#}
    {#    <h1><span class="blue">&lt;</span>Products<span class="blue">&gt;</span> <span class="yellow">List</span></h1>#}
    {#    <br>#}
    {#    <h2>Created with love by <a href="https://www.linkedin.com/in/abdullah-al-galib/" target="_blank">Siyam Al Galib</a></h2>#}

    <!--Filter-->

    <div class="col-lg-12">

        <form action="{% url 'product:search' %}" method="post">
        {% csrf_token %}

            <div class="col-lg-3">
                <br><br>
                <div class="form-group">
                    <label for="sel1">BRAND</label>
                    <select name="brand" class="form-control">
                        <option value="">...</option>
                        {% for brand in brands %}
                            <option  value="{{ brand.id }}">{{ brand }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="col-lg-3">
                <br><br>
                <div class="form-group">
                    <label for="sel1">CATEGORY</label>
                    <select name="category" class="form-control">
                        <option value="">...</option>
                        {% for category in categories %}
                            <option  value="{{ category.id }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="col-lg-3">
                <br><br>
                <div class="form-group">
                    <label for="sel1">STATUS</label>
                    <select name="status" class="form-control">
                        <option value="">...</option>
                        {% for status in statuses %}
                            <option  value="{{ status.0 }}">{{ status.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-lg-3">
                <br><br><br>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Submit</button>
                </div>
            </div>

        </form>
    </div>

    <!--Table-->
    <table class="table table-bordered">
        <thead>
        <tr>
            <th><h1>Name</h1></th>
            <th><h1>Price</h1></th>
            <th><h1>Status</h1></th>
            <th><h1>Category</h1></th>
            <th><h1>Brand</h1></th>
            <th><h1>Description</h1></th>
        </tr>
        </thead>

        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.status }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.brand }}</td>
                <td>{{ product.description }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>

    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"#}
    {#              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>#}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
</head>

<body>

<div class="container">
    <div class="row">

        {% block content %}

        {% endblock %}

    </div>
</div>


<!--Bootstrap4 CDN JS-->
{#	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">#}
{#	</script>#}
{#	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"#}
{#		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">#}
{#	</script>#}
{#	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"#}
{#		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">#}
{#	</script>#}
<!--Bootstrap4 CDN JS-->

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>

<body>
    <h1>Welcome Home!</h1>
</body>
</html>